[build]
builder = "nixpacks"
watchPatterns = ["backend/**/*.js"]

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on-failure"

[deploy.envs]
NODE_ENV = "production"
